
spring:
  profiles:
    include: oauth
#  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    name: sa
#    password:
#  h2:
#    console:
#      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '1234'
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
      database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create